version: '3'

networks:
  web:
    external: true
  internal:
    external: false

services:
  vkb:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/vkb
    labels:
      - traefik.http.routers.vkb.rule=Host(`vkb.platfom.live`)
      - traefik.http.routers.vkb.tls=true
      - traefik.http.routers.vkb.tls.certresolver=lets-encrypt
      - traefik.port=8000  
    networks:
      - web
      - internal  